### ISSUE TITLE
Change: make the game in center always

### ISSUE THREAD

**Issue by Anshgrover23** [Anshgrover23/Rock-Paper-Scissors-Game#1]
Reference Screenshot: 
![Screenshot (82)](https://github.com/Anshgrover23/Rock-Paper-Scissors-Game/assets/168731971/2dfbbee1-d6e0-48e7-b588-e1862999ce6c)

**Comment by Katielee25** [comment]
Hi can i take this?

**Comment by Anshgrover23** [comment]
@Katielee25 yes sure why not? and thanks for taking this
